#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 06 10:03:42 CET 2018
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim masterbench_behav -key {Behavioral:sim_1:Functional:masterbench} -tclbatch masterbench.tcl -view /home/tibo36/Documents/Info-SI/Master/M1S1/AEO/TP_9good/TP_9good.srcs/sim_1/imports/nexys3V6_vivado/masterbench_behav.wcfg -log simulate.log
