webtalk_init -webtalk_dir /home/tibo36/Documents/Info-SI/Master/M1S1/AEO/TP_10.1/TP_10.1.sim/sim_1/behav/xsim/xsim.dir/masterbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 12 16:07:17 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d69ccf93-f5be-4a60-a99c-ed8bf688a253" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b2b23aa9cb164b759cd59a646aa9a2c4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3100.658 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10280 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "11.40_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125880_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3659595436 -regid "" -xml /home/tibo36/Documents/Info-SI/Master/M1S1/AEO/TP_10.1/TP_10.1.sim/sim_1/behav/xsim/xsim.dir/masterbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tibo36/Documents/Info-SI/Master/M1S1/AEO/TP_10.1/TP_10.1.sim/sim_1/behav/xsim/xsim.dir/masterbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tibo36/Documents/Info-SI/Master/M1S1/AEO/TP_10.1/TP_10.1.sim/sim_1/behav/xsim/xsim.dir/masterbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
